#!/bin/sh
pkg install -y -r pkg.domarino.com \
    devel/p5-App-cpanminus \
    devel/p5-Dist-Zilla \
    p5-Net-LibIDN \
    gmake \
    p5-XML-SAX-Expat \
    texlive-full \
    File-MimeInfo \
    devel/git

mkdir -p /usr/local/d8o/hase /usr/local/d8o/ansible
mount -t nullfs /projects/ideegeo/hase/     /jails/z2/usr/local/d8o/hase
mount -t nullfs /projects/ideegeo/ansible/  /jails/z2/usr/local/d8o/ansible
cd /usr/local/d8o/hase/perl
dzil authordeps | cpanm -n
dzil build
cpanm -n /usr/local/d8o/ansible/files/perl_modules/Daemonise.tgz
cpanm -n /usr/local/d8o/ansible/files/perl_modules/Net-DNS-Abstract.tgz
cpanm -n /usr/local/d8o/ansible/files/perl_modules/D8o-DNS.tgz

dzil install
